### ISSUE TITLE
GraphBLAS no longer compiles with CUDA enabled

### ISSUE THREAD

**Issue by DrTimothyAldenDavis** [DrTimothyAldenDavis/SuiteSparse#396]
https://github.com/DrTimothyAldenDavis/SuiteSparse/blob/6c966bd5112dedab5a7d5799166f7feb503b8483/GraphBLAS/CMakeLists.txt#L27

I'm getting back to the CUDA kernels for GraphBLAS.  They are not enabled in production.

If I enable CUDA in the GraphBLAS/CMakeLists.txt file, I get a build error.  The CUDA library gets configured but the top-level CMakeLists.txt files with an error (target "graphblascuda" not found).

This worked in GraphBLAS v8.0.2 (the cmake would build but there was a compilation error later on because of other issues in how complex types are handled, but that's another issue).  The build now fails earlier; see below.

@mmuetzel :  this is failing because of the recent updates to the GraphBLAS/CMakeLists.txt file, with the new `export (EXPORT GraphBLASTargets ...)` and `install ( EXPORT GraphBLASTargets ...)` commands.  Is there something missing there when CUDA is enabled?

```
hypersparse $ make
( cd build && cmake  .. && cmake --build . --config Release -j8 )
-- Building SuiteSparse:GraphBLAS version: v8.2.0, date: Sept 8, 2023
-- GraphBLAS C API: v2.0, date: Nov 15, 2021
-- Source:        /home/faculty/d/davis/dev2/SuiteSparse/GraphBLAS 
-- Build:         /home/faculty/d/davis/dev2/SuiteSparse/GraphBLAS/build 
-- The C compiler identification is GNU 9.4.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Install lib:     lib
-- Install include: include
-- Install bin:     bin
-- Install rpath:   
-- Build   rpath:   /home/faculty/d/davis/dev2/SuiteSparse/GraphBLAS/build
-- Build type:    Release 
-- Looking for a Fortran compiler
-- Looking for a Fortran compiler - /usr/bin/f95
-- The Fortran compiler identification is GNU 9.4.0
-- Detecting Fortran compiler ABI info
-- Detecting Fortran compiler ABI info - done
-- Check for working Fortran compiler: /usr/bin/f95 - skipped
-- Fortran: /usr/bin/f95
-- Looking for a CUDA compiler
-- Looking for a CUDA compiler - /usr/local/cuda/bin/nvcc
-- Looking for CUDA
-- Find CUDA tool kit:
-- Found CUDAToolkit: /usr/local/cuda/include (found version "11.7.99") 
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- CUDA toolkit found:   TRUE
-- CUDA toolkit version: 11.7.99
-- CUDA toolkit include: /usr/local/cuda/include
-- CUDA toolkit lib dir: /usr/local/cuda/lib64
-- The CUDA compiler identification is NVIDIA 11.7.99
-- Detecting CUDA compiler ABI info
-- Detecting CUDA compiler ABI info - done
-- Check for working CUDA compiler: /usr/local/cuda/bin/nvcc - skipped
-- Detecting CUDA compile features
-- Detecting CUDA compile features - done
-- CUDA: enabled
-- Performing Test HAVE_GETENV_HOME
-- Performing Test HAVE_GETENV_HOME - Success
-- getenv("HOME"): available
-- GraphBLAS CPU JIT: enabled
-- GBCOMPACT: enabled; FactoryKernels will not be built
-- GraphBLAS CUDA JIT: enabled
-- The CXX compiler identification is GNU 9.4.0
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- C++ flags for CUDA:  --std=c++17 -fPIC 
-- RMM_WRAP_INCLUDES: ../rmm_wrap
-- GraphBLAS CUDA includes: ../rmm_wrap;../Source;../Source/Shared;../Source/Template;../Source/Factories;../Include;../CUDA
-- Found Python: /opt/intel/oneapi/intelpython/latest/bin/python3.9 (found version "3.9.7") found components: Interpreter 
-- CUDA tests files: 
-- Found CUDA: /usr/local/cuda (found version "11.7") 
Cloning into 'spdlog'...
Note: switching to '76fb40d95455f249bd70824ecfcae7a8f0930fa3'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by switching back to a branch.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -c with the switch command. Example:

  git switch -c <new-branch-name>

Or undo this operation with:

  git switch -

Turn off this advice by setting config variable advice.detachedHead to false

Cloning into 'rmm'...
-- Found OpenMP_C: -fopenmp (found version "4.5") 
-- Found OpenMP_Fortran: -fopenmp (found version "4.5") 
-- Found OpenMP: TRUE (found version "4.5")  
-- cpu_features (by google.com): enabled 
-- Building dynamic GraphBLAS library
-- Looking for dlfcn.h
-- Looking for dlfcn.h - found
-- cpu_feautures has dlfcn.h
-- Looking for getauxval
-- Looking for getauxval - found
-- cpu_feautures has getauxval from sys/auxv.h
-- Performing Test TEST_FOR_STDATOMIC
-- Performing Test TEST_FOR_STDATOMIC - Success
-- ANSI C11 atomics: OK. -latomic not needed
-- CMAKE OpenMP libraries:    /usr/lib/gcc/x86_64-linux-gnu/9/libgomp.so;/usr/lib/x86_64-linux-gnu/libpthread.so
-- CMAKE OpenMP include:      
-- CMAKE OpenMP C flags:      -fopenmp
-- CMAKE C flags:  -DSUITESPARSE_CUDA -Wundef  -std=c11 -lm -Wno-pragmas  -fexcess-precision=fast  -fcx-limited-range  -fno-math-errno  -fwrapv  -O3 -DNDEBUG -fopenmp  
-- Skipping the demos in GraphBLAS/Demo
-- ------------------------------------------------------------------------
-- JIT configuration:
-- ------------------------------------------------------------------------
-- JIT C compiler: /usr/bin/cc
-- JIT C flags:     -DSUITESPARSE_CUDA -Wundef  -std=c11 -lm -Wno-pragmas  -fexcess-precision=fast  -fcx-limited-range  -fno-math-errno  -fwrapv  -O3 -DNDEBUG -fopenmp  -fPIC 
-- JIT link flags:  -shared 
-- JIT lib prefix: lib
-- JIT lib suffix: .so
-- JIT obj suffix: .o
-- JIT cache:      /home/faculty/d/davis/.SuiteSparse/GrB8.2.0
-- JIT openmp inc: 
-- JIT openmp dirs 
-- JIT libraries:   -lm -ldl /usr/lib/gcc/x86_64-linux-gnu/9/libgomp.so /usr/lib/x86_64-linux-gnu/libpthread.so
-- JIT cmake libs: m;dl;/usr/lib/gcc/x86_64-linux-gnu/9/libgomp.so;/usr/lib/x86_64-linux-gnu/libpthread.so
-- ------------------------------------------------------------------------
-- SuiteSparse CMAKE report for: graphblas
-- ------------------------------------------------------------------------
-- inside common SuiteSparse root:  false
-- install in SuiteSparse/lib and SuiteSparse/include: OFF
-- build type:           Release
-- NSTATIC:              true (do not build static library)
-- use OpenMP:           yes 
-- C compiler:           /usr/bin/cc 
-- C flags:               -DSUITESPARSE_CUDA -Wundef  -std=c11 -lm -Wno-pragmas  -fexcess-precision=fast  -fcx-limited-range  -fno-math-errno  -fwrapv  -O3 -DNDEBUG -fopenmp 
-- C++ compiler:         /usr/bin/c++
-- C++ flags:            
-- C Flags release:      -O3 -DNDEBUG 
-- C++ Flags release:    -O3 -DNDEBUG 
-- Fortran compiler:     /usr/bin/f95 
-- compile definitions:  SUITESPARSE_CUDA;GBCOMPACT
-- CUDA architectures:   52;75;80
-- ------------------------------------------------------------------------
-- Configuring done (17.5s)
CMake Error: install(EXPORT "GraphBLASTargets" ...) includes target "GraphBLAS" which requires target "graphblascuda" that is not in any export set.
CMake Error in CMakeLists.txt:
  export called with target "GraphBLAS" which requires target "graphblascuda"
  that is not in any export set.


-- Generating done (0.2s)
CMake Generate step failed.  Build files cannot be regenerated correctly.
make: *** [Makefile:31: library] Error 1

```

**Comment by mmuetzel** [comment]
Hmm...
There was no `FindGraphBLAS_CUDA.cmake`. So, I missed that there is another target that would need to be exported.

It's probably not too hard to export a `SuiteSparse::GraphBLAS_CUDA` target. But I'm not set up to actually test it.

I can try my best though...

**Comment by mmuetzel** [comment]
Does #397 help?

**Comment by DrTimothyAldenDavis** [comment]
Yes, #397 fixes this issue -- thanks!
