### PR TITLE
ParU: Don't build with OpenMP before version 4.5

### LINKED ISSUE #462: ParU fails with OpenMP from MSVC
**Describe the bug**
When trying to build ParU with an MSVC toolchain, compilation fails with errors like the following:
```
  D:\a\SuiteSparse\SuiteSparse\ParU\Source\paru_analyze.cpp(1060): error C3001: 'taskloop': expected an OpenMP directive name
  D:\a\SuiteSparse\SuiteSparse\ParU\Source\paru_analyze.cpp(1068): error C3001: 'taskloop': expected an OpenMP directive name
  D:\a\SuiteSparse\SuiteSparse\ParU\Source\paru_analyze.cpp(1300): error C3001: 'taskloop': expected an OpenMP directive name
  D:\a\SuiteSparse\SuiteSparse\ParU\Source\paru_analyze.cpp(1314): error C3001: 'taskloop': expected an OpenMP directive name
  [3/84] Building CXX object CMakeFiles\paru.dir\Release\Source\paru_assemble.cpp.obj
  FAILED: CMakeFiles/paru.dir/Release/Source/paru_assemble.cpp.obj 
```
Afaict, the `taskloop` construct was introduced with OpenMP 4.5. MSVC supports only OpenMP 2.0.

**To Reproduce**
Try to build ParU with OpenMP using MSVC (see CI) or another toolchain that lacks support for OpenMP 4.5.

**Expected behavior**
ParU builds without error.

**Desktop (please complete the following information):**
 - OS: Windows
 - compiler MSVC 2022

### PR DESCRIPTION
**Pull request by mmuetzel**
Fixes #462.

### CODE REVIEW

**Comment by DrTimothyAldenDavis** [comment]
Thanks -- looks great!
