### ISSUE TITLE
[ParU] paru_init_rowFronts.cpp:443:63: error: Sym is predetermined shared for shared

### ISSUE THREAD

**Issue by gruenich** [DrTimothyAldenDavis/SuiteSparse#1057]
While updating openSuse's SuiteSparse package, I noticed that for SLES 15.6 and 15.7 compilation failed. It works with SLES 16.0. The error message looks strange. Might be related to the compiler which is GCC 7.5.0.  
Sorry, I am just dumping the output, I did not analyse this in more detail. Just close this issue, if it is of no interest for you.

```
[   89s] [ 56%] Building CXX object CMakeFiles/ParU.dir/Source/paru_init_rowFronts.cpp.o
[   89s] /usr/bin/c++ -DBLAS_OpenBLAS -DParU_EXPORTS -DSUITESPARSE_HAVE_OPENBLAS_SET_NUM_THREADS_LOCAL -I/home/abuild/rpmbuild/BUILD/SuiteSparse-7.12.3/ParU/build -I/home/abuild/rpmbuild/BUILD/SuiteSparse-7.12.3/ParU -I/home/abuild/rpmbuild/BUILD/SuiteSparse-7.12.3/ParU/Source -I/home/abuild/rpmbuild/BUILD/SuiteSparse-7.12.3/ParU/Include -I/home/abuild/rpmbuild/BUILD/SuiteSparse-7.12.3/SuiteSparse_config -I/home/abuild/rpmbuild/BUILD/SuiteSparse-7.12.3/UMFPACK/Include -I/home/abuild/rpmbuild/BUILD/SuiteSparse-7.12.3/AMD/Include -I/home/abuild/rpmbuild/BUILD/SuiteSparse-7.12.3/CHOLMOD/Include -O2 -g -DNDEBUG -std=gnu++11 -fPIC -fopenmp -MD -MT CMakeFiles/ParU.dir/Source/paru_init_rowFronts.cpp.o -MF CMakeFiles/ParU.dir/Source/paru_init_rowFronts.cpp.o.d -o CMakeFiles/ParU.dir/Source/paru_init_rowFronts.cpp.o -c /home/abuild/rpmbuild/BUILD/SuiteSparse-7.12.3/ParU/Source/paru_init_rowFronts.cpp
[   89s] /home/abuild/rpmbuild/BUILD/SuiteSparse-7.12.3/ParU/Source/paru_init_rowFronts.cpp: In function 'ParU_Info paru_init_rowFronts(paru_work*, ParU_Numeric_struct**, cholmod_sparse*, ParU_Symbolic)':
[   89s] /home/abuild/rpmbuild/BUILD/SuiteSparse-7.12.3/ParU/Source/paru_init_rowFronts.cpp:443:63: error: 'Sym' is predetermined 'shared' for 'shared'
[   89s]              shared(Sym, Diag_map, inv_Diag_map) grainsize(512)
[   89s]                                                                ^
[   89s] gmake[4]: *** [CMakeFiles/ParU.dir/build.make:555: CMakeFiles/ParU.dir/Source/paru_init_rowFronts.cpp.o] Error 1
[   89s] gmake[4]: Leaving directory '/home/abuild/rpmbuild/BUILD/SuiteSparse-7.12.3/ParU/build'
[   89s] gmake[4]: *** Waiting for unfinished jobs....
[   89s] gmake[4]: Entering directory '/home/abuild/rpmbuild/BUILD/SuiteSparse-7.12.3/ParU/build'
```

**Comment by DrTimothyAldenDavis** [comment]
Thanks for catching that.  I’d like to diagnose it and fix it if possible.
I don’t know if I can fix it though. It might be an issue that means ParU
can’t be compiled with an older g++ version. I’ve found that C++ is like
that.

I can try using gcc 7.4.0 from spack to see if I can replicate it. Spack
doesn’t have 7.5.0.

**Comment by DrTimothyAldenDavis** [comment]
Digging deeper ... that's an issue with OpenMP 3.1 used in gcc 7.5.0.  ParU requires OpenMP 4.5.

The cmake script tries to guard against this by emitting an error when an older OpenMP is used.  However, that test can fail if Intel OpenMP is being used with an older cmake.

It would be possible to fix this one error but there will be many others since ParU makes significant use of OpenMP 4.5 features.

Can you try compiling without OpenMP on those two platforms?  ParU will be slower, of course, but there's no way it can work with OpenMP 3.1.

https://github.com/DrTimothyAldenDavis/SuiteSparse/blob/c9d7ec42177bce035bd646ffa6868c592533c82b/ParU/CMakeLists.txt#L58-L75

**Comment by DrTimothyAldenDavis** [comment]
Can you post more of the cmake output where these messages about OpenMP will appear?

**Comment by gruenich** [comment]
It claims to have found OpenMP 4.5 - at least for C.

```
make[1]: Entering directory '/home/abuild/rpmbuild/BUILD/SuiteSparse-7.12.3/SuiteSparse_config'
[   32s] ( cd build && cmake -DCMAKE_INSTALL_PREFIX:PATH=/usr \
[   32s]         -DBLA_VENDOR=OpenBLAS \
[   32s]         -DCMAKE_INSTALL_BINDIR:PATH=/usr/bin \
[   32s]         -DCMAKE_INSTALL_SBINDIR:PATH=/usr/sbin \
[   32s]         -DCMAKE_INSTALL_LIBEXECDIR:PATH=/usr/lib \
[   32s]         -DCMAKE_INSTALL_SYSCONFDIR:PATH=/etc \
[   32s]         -DCMAKE_INSTALL_SHAREDSTATEDIR:PATH=/var/lib \
[   32s]         -DCMAKE_INSTALL_LOCALSTATEDIR:PATH=/var \
[   32s]         -DCMAKE_INSTALL_RUNSTATEDIR:PATH=/run \
[   32s]         -DCMAKE_INSTALL_LIBDIR:PATH=/usr/lib64 \
[   32s]         -DCMAKE_INSTALL_INCLUDEDIR:PATH=/usr/include \
[   32s]         -DCMAKE_INSTALL_DATAROOTDIR:PATH=/usr/share \
[   32s]         -DCMAKE_SKIP_INSTALL_RPATH:BOOL=ON \
[   32s]         -DINCLUDE_INSTALL_DIR:PATH=/usr/include \
[   32s]         -DLIB_INSTALL_DIR:PATH=/usr/lib64 \
[   32s]         -DSYSCONF_INSTALL_DIR:PATH=/etc \
[   32s]         -DSHARE_INSTALL_PREFIX:PATH=/usr/share \
[   32s]         -DCMAKE_BUILD_TYPE=RelWithDebInfo \
[   32s]         -DCMAKE_C_FLAGS="" \
[   32s]         -DCMAKE_CXX_FLAGS="" \
[   32s]         -DCMAKE_Fortran_FLAGS="" \
[   32s]         -DCMAKE_EXE_LINKER_FLAGS="-lm -Wl,--as-needed -Wl,-z,now" \
[   32s]         -DCMAKE_MODULE_LINKER_FLAGS="-lm -Wl,--as-needed" \
[   32s]         -DCMAKE_SHARED_LINKER_FLAGS="-lm -Wl,--as-needed -Wl,-z,now" \
[   32s]         -DLIB_SUFFIX=64 \
[   32s]         -DCMAKE_VERBOSE_MAKEFILE:BOOL=ON \
[   32s]         -DBUILD_SHARED_LIBS:BOOL=ON \
[   32s]         -DBUILD_STATIC_LIBS:BOOL=OFF \
[   32s]         -DCMAKE_COLOR_MAKEFILE:BOOL=OFF \
[   32s]         -DCMAKE_INSTALL_DO_STRIP:BOOL=OFF \
[   32s]         -DCMAKE_MODULES_INSTALL_DIR=/usr/lib64/cmake/suitesparse \
[   32s]         -DSUITESPARSE_DEMOS=ON \
[   32s]         -DBUILD_TESTING=ON .. && cmake --build . --config Release -j4 )
[   32s] -- Building SuiteSparse_config version: v7.12.3 (July 31, 2026)
[   32s] -- The C compiler identification is GNU 7.5.0
[   32s] -- Detecting C compiler ABI info
[   32s] -- Detecting C compiler ABI info - done
[   32s] -- Check for working C compiler: /usr/bin/cc - skipped
[   32s] -- Detecting C compile features
[   32s] -- Detecting C compile features - done
[   32s] -- Source:           /home/abuild/rpmbuild/BUILD/SuiteSparse-7.12.3/SuiteSparse_config 
[   32s] -- Build:            /home/abuild/rpmbuild/BUILD/SuiteSparse-7.12.3/SuiteSparse_config/build 
[   32s] -- Install lib:      /usr/lib64
[   32s] -- Install include:  /usr/include/suitesparse
[   32s] -- Install bin:      /usr/bin
[   32s] -- Install pkg-file: /usr/lib64
[   32s] -- Install rpath:    $ORIGIN
[   32s] -- Build   rpath:    
[   32s] -- Build type:       RelWithDebInfo 
[   32s] -- Checking if Fortran is available and compatible with C/C++
[   32s] -- Looking for a Fortran compiler
[   32s] -- Looking for a Fortran compiler - /usr/bin/gfortran
[   32s] -- The CXX compiler identification is GNU 7.5.0
[   32s] -- Detecting CXX compiler ABI info
[   32s] -- Detecting CXX compiler ABI info - done
[   32s] -- Check for working CXX compiler: /usr/bin/c++ - skipped
[   32s] -- Detecting CXX compile features
[   32s] -- Detecting CXX compile features - done
[   32s] -- The Fortran compiler identification is GNU 7.5.0
[   32s] -- Detecting Fortran compiler ABI info
[   32s] -- Detecting Fortran compiler ABI info - done
[   32s] -- Check for working Fortran compiler: /usr/bin/gfortran - skipped
[   32s] -- Fortran:          enabled
[   32s] -- Looking for a CUDA compiler
[   32s] -- Looking for a CUDA compiler - NOTFOUND
[   32s] -- CUDA:             not found
[   32s] -- CUDA:             not enabled
[   32s] -- Found OpenMP_C: -fopenmp (found version "4.5") 
[   32s] -- Found OpenMP: TRUE (found version "4.5") found components: C 
[   32s] -- OpenMP C libraries: /usr/lib64/gcc/x86_64-suse-linux/7/libgomp.so;/usr/lib64/libpthread.a 
[   32s] -- SuiteSparse_config has OpenMP: ON
[   32s] -- Looking for clock_gettime
[   32s] -- Looking for clock_gettime - found
[   32s] -- Using clock_gettime without librt
[   32s] -- Looking for 32-BLAS: OpenBLAS
[   32s] -- Looking for Fortran sgemm
[   32s] -- Looking for Fortran sgemm - found
[   32s] -- Found BLAS: /usr/lib64/libopenblas.so  
[   32s] -- Found OpenBLAS 32-bit BLAS
[   32s] -- BLAS: OpenBLAS v0.3.27 or later: single-threaded
[   32s] -- Specific BLAS: OpenBLAS found: TRUE
[   32s] -- BLAS integer size: 4
[   32s] -- BLAS libraries:      /usr/lib64/libopenblas.so 
[   32s] -- BLAS linker flags:    
[   32s] -- BLAS include:         
[   32s] -- Detecting Fortran/C Interface
[   32s] -- Detecting Fortran/C Interface - Found GLOBAL and MODULE mangling
[   32s] -- C to Fortran calling protocol: 
[   32s] --     SUITESPARSE_HAS_FORTRAN  : ON
[   32s] --     FortranCInterface_GLOBAL_MACRO  : (name,NAME) name##_
[   32s] --     FortranCInterface_GLOBAL__MACRO : (name,NAME) name##_
[   32s] -- Looking for fmax
[   32s] -- Looking for fmax - not found
[   32s] -- OpenMP C libraries:      /usr/lib64/gcc/x86_64-suse-linux/7/libgomp.so;/usr/lib64/libpthread.a 
[   32s] -- OpenMP C include:         
[   32s] -- OpenMP C flags:          -fopenmp 
[   32s] -- ------------------------------------------------------------------------
[   32s] -- SuiteSparse CMAKE report for: SuiteSparseConfig
[   32s] -- ------------------------------------------------------------------------
[   32s] -- inside common SuiteSparse root:  OFF
[   32s] -- install in SuiteSparse/lib and SuiteSparse/include: OFF
[   32s] -- build type:           RelWithDebInfo
[   32s] -- BUILD_SHARED_LIBS:    ON
[   32s] -- BUILD_STATIC_LIBS:    OFF
[   32s] -- C compiler:           /usr/bin/cc 
[   32s] -- C flags:              
[   32s] -- C++ compiler:         /usr/bin/c++
[   32s] -- C++ flags:            
[   32s] -- C Flags release:      -O3 -DNDEBUG 
[   32s] -- C++ Flags release:    -O3 -DNDEBUG 
[   32s] -- Fortran compiler:     /usr/bin/gfortran 
[   32s] -- compile definitions:  BLAS_OpenBLAS;SUITESPARSE_HAVE_OPENBLAS_SET_NUM_THREADS_LOCAL
[   32s] -- BLAS integer:         int32_t
[   32s] -- ------------------------------------------------------------------------
[   32s] -- CMAKE_SYSTEM_PROCESSOR: x86_64
[   32s] -- Configuring done (2.5s)
[   32s] -- Generating done (0.0s)
[   32s] CMake Warning:
[   32s]   Manually-specified variables were not used by the project:
[   32s] 
[   32s]     BUILD_TESTING
[   32s]     CMAKE_INSTALL_DO_STRIP
[   32s]     CMAKE_MODULES_INSTALL_DIR
[   32s]     INCLUDE_INSTALL_DIR
[   32s]     LIB_INSTALL_DIR
[   32s]     LIB_SUFFIX
[   32s]     SHARE_INSTALL_PREFIX
[   32s]     SYSCONF_INSTALL_DIR
[   32s] 
[   32s] 
[   32s] -- Build files have been written to: /home/abuild/rpmbuild/BUILD/SuiteSparse-7.12.3/SuiteSparse_config/build
[   32s] Change Dir: '/home/abuild/rpmbuild/BUILD/SuiteSparse-7.12.3/SuiteSparse_config/build'
```

**Comment by mmuetzel** [comment]
Afaict, `Sym` is `const` in that context. So, it doesn't need to be mentioned at all in the OpenMP directive. Maybe, some compilers are more picky when it comes to that (and even resort to throwing errors).
Does it build with the following modification?
``` diff
 ParU/Source/paru_init_rowFronts.cpp | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)

diff --git a/ParU/Source/paru_init_rowFronts.cpp b/ParU/Source/paru_init_rowFronts.cpp
index d688be721..be284cef0 100644
--- a/ParU/Source/paru_init_rowFronts.cpp
+++ b/ParU/Source/paru_init_rowFronts.cpp
@@ -440,7 +440,7 @@ ParU_Info paru_init_rowFronts
     if (Diag_map)
     {
         #pragma omp taskloop default(none) \
-            shared(Sym, Diag_map, inv_Diag_map) grainsize(512)
+            shared(Diag_map, inv_Diag_map) grainsize(512)
         for (int64_t i = 0; i < Sym->n; i++)
         {
             Diag_map[i] = Sym->Diag_map[i];
```

**Comment by DrTimothyAldenDavis** [comment]
I did a search and it looks like gcc 7.5.0 uses the OpenMP 3.1 rule for data sharing, for supporting legacy codes.  That's why it's producing this error even though it supports OpenMP 4.5.

So removing "Sym" from the list should fix the problem.  I'll make that change on my side, but I can't test it with gcc 7.5.0

**Comment by DrTimothyAldenDavis** [comment]
The "default(none)" also needs to be removed, I think.  Removing just "sym" causes an error with gcc 14.2.

**Comment by DrTimothyAldenDavis** [comment]
Can you give this a try on the dev2 branch?  See https://github.com/DrTimothyAldenDavis/SuiteSparse/pull/1059 .

**Comment by DrTimothyAldenDavis** [comment]
This is fixed in SuiteSparse v7.13.0, with ParU v1.1.2.  See https://github.com/DrTimothyAldenDavis/SuiteSparse/releases/tag/v7.13.0 .  Can you give this a try to confirm that the issue is resolved?

**Comment by gruenich** [comment]
Yes, works for openSuse! Thanks to your fix, the builds for SUSE 15.6 and 15.7 are passing for 7.13.0!

**Comment by DrTimothyAldenDavis** [comment]
Great!  Thanks for the feedback.
